// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3333' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: {
        status: 'ok';
        uptime: number;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostAuthSignupTrainerData = {
    body: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/signup/trainer';
};

export type PostAuthSignupTrainerErrors = {
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PostAuthSignupTrainerError = PostAuthSignupTrainerErrors[keyof PostAuthSignupTrainerErrors];

export type PostAuthSignupTrainerResponses = {
    /**
     * Default Response
     */
    201: {
        accessToken: string;
        refreshToken: string;
        user: {
            id: string;
            name: string;
            email: string;
            role: 'trainer' | 'student';
        };
    };
};

export type PostAuthSignupTrainerResponse = PostAuthSignupTrainerResponses[keyof PostAuthSignupTrainerResponses];

export type PostAuthSignupStudentData = {
    body: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/signup/student';
};

export type PostAuthSignupStudentErrors = {
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PostAuthSignupStudentError = PostAuthSignupStudentErrors[keyof PostAuthSignupStudentErrors];

export type PostAuthSignupStudentResponses = {
    /**
     * Default Response
     */
    201: {
        accessToken: string;
        refreshToken: string;
        user: {
            id: string;
            name: string;
            email: string;
            role: 'trainer' | 'student';
        };
    };
};

export type PostAuthSignupStudentResponse = PostAuthSignupStudentResponses[keyof PostAuthSignupStudentResponses];

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
        role: 'trainer' | 'student';
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Default Response
     */
    401: {
        error: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        refreshToken: string;
        user: {
            id: string;
            name: string;
            email: string;
            role: 'trainer' | 'student';
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Default Response
     */
    401: {
        error: string;
    };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetStudentsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        status?: 'active' | 'inactive' | 'paused';
        limit?: number;
        offset?: number;
    };
    url: '/students';
};

export type GetStudentsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            trainerId: string | null;
            isIndependent: boolean;
            name: string;
            email: string | null;
            phone: string | null;
            birthDate: string | null;
            gender: 'male' | 'female' | 'other';
            goals: string | null;
            restrictions: string | null;
            status: 'active' | 'inactive' | 'paused';
            avatarUrl: string | null;
            createdAt: string;
        }>;
        total: number;
    };
};

export type GetStudentsResponse = GetStudentsResponses[keyof GetStudentsResponses];

export type PostStudentsData = {
    body: {
        name: string;
        email?: string;
        phone?: string;
        birthDate?: string;
        gender?: 'male' | 'female' | 'other';
        goals?: string;
        restrictions?: string;
        status?: 'active' | 'inactive' | 'paused';
    };
    path?: never;
    query?: never;
    url: '/students';
};

export type PostStudentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        createdAt: string;
    };
};

export type PostStudentsResponse = PostStudentsResponses[keyof PostStudentsResponses];

export type DeleteStudentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type DeleteStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetStudentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type GetStudentsByIdErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetStudentsByIdError = GetStudentsByIdErrors[keyof GetStudentsByIdErrors];

export type GetStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        createdAt: string;
    };
};

export type GetStudentsByIdResponse = GetStudentsByIdResponses[keyof GetStudentsByIdResponses];

export type PatchStudentsByIdData = {
    body: {
        name?: string;
        email?: string;
        phone?: string;
        birthDate?: string;
        gender?: 'male' | 'female' | 'other';
        goals?: string;
        restrictions?: string;
        status?: 'active' | 'inactive' | 'paused';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type PatchStudentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchStudentsByIdError = PatchStudentsByIdErrors[keyof PatchStudentsByIdErrors];

export type PatchStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        createdAt: string;
    };
};

export type PatchStudentsByIdResponse = PatchStudentsByIdResponses[keyof PatchStudentsByIdResponses];

export type GetExercisesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        muscleGroup?: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        scope?: 'mine' | 'global' | 'all';
        limit?: number;
        offset?: number;
    };
    url: '/exercises';
};

export type GetExercisesResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            trainerId: string | null;
            name: string;
            muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
            equipment: string | null;
            videoUrl: string | null;
            instructions: string | null;
            createdAt: string | string;
        }>;
        total: number;
    };
};

export type GetExercisesResponse = GetExercisesResponses[keyof GetExercisesResponses];

export type PostExercisesData = {
    body: {
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment?: string;
        videoUrl?: string;
        instructions?: string;
    };
    path?: never;
    query?: never;
    url: '/exercises';
};

export type PostExercisesResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        trainerId: string | null;
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment: string | null;
        videoUrl: string | null;
        instructions: string | null;
        createdAt: string | string;
    };
};

export type PostExercisesResponse = PostExercisesResponses[keyof PostExercisesResponses];

export type DeleteExercisesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type DeleteExercisesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchExercisesByIdData = {
    body: {
        name?: string;
        muscleGroup?: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment?: string;
        videoUrl?: string;
        instructions?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type PatchExercisesByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchExercisesByIdError = PatchExercisesByIdErrors[keyof PatchExercisesByIdErrors];

export type PatchExercisesByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment: string | null;
        videoUrl: string | null;
        instructions: string | null;
        createdAt: string | string;
    };
};

export type PatchExercisesByIdResponse = PatchExercisesByIdResponses[keyof PatchExercisesByIdResponses];

export type GetStudentsByStudentIdAssessmentsData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/students/{studentId}/assessments';
};

export type GetStudentsByStudentIdAssessmentsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            date: string;
            weightKg: string | number | null;
            heightCm: string | number | null;
            bodyFatPct: string | number | null;
            measurements: {
                chest?: number;
                waist?: number;
                hip?: number;
                armRight?: number;
                armLeft?: number;
                thighRight?: number;
                thighLeft?: number;
                calfRight?: number;
                calfLeft?: number;
            } | null;
            photos: Array<string> | null;
            notes: string | null;
            createdAt: string | string;
        }>;
        total: number;
    };
};

export type GetStudentsByStudentIdAssessmentsResponse = GetStudentsByStudentIdAssessmentsResponses[keyof GetStudentsByStudentIdAssessmentsResponses];

export type PostStudentsByStudentIdAssessmentsData = {
    body: {
        date: string;
        weightKg?: number;
        heightCm?: number;
        bodyFatPct?: number;
        measurements?: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        };
        photos?: Array<string>;
        notes?: string;
    };
    path: {
        studentId: string;
    };
    query?: never;
    url: '/students/{studentId}/assessments';
};

export type PostStudentsByStudentIdAssessmentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type PostStudentsByStudentIdAssessmentsResponse = PostStudentsByStudentIdAssessmentsResponses[keyof PostStudentsByStudentIdAssessmentsResponses];

export type DeleteAssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type DeleteAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type GetAssessmentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetAssessmentsByIdError = GetAssessmentsByIdErrors[keyof GetAssessmentsByIdErrors];

export type GetAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type GetAssessmentsByIdResponse = GetAssessmentsByIdResponses[keyof GetAssessmentsByIdResponses];

export type PatchAssessmentsByIdData = {
    body: {
        date?: string;
        weightKg?: number;
        heightCm?: number;
        bodyFatPct?: number;
        measurements?: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        };
        photos?: Array<string>;
        notes?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type PatchAssessmentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchAssessmentsByIdError = PatchAssessmentsByIdErrors[keyof PatchAssessmentsByIdErrors];

export type PatchAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type PatchAssessmentsByIdResponse = PatchAssessmentsByIdResponses[keyof PatchAssessmentsByIdResponses];

export type PostWorkoutPlansData = {
    body: {
        studentId: string;
        name: string;
        startDate?: string;
        endDate?: string;
        status?: 'active' | 'archived' | 'draft';
        notes?: string;
        days: Array<{
            label: string;
            dayOrder: number;
            exercises: Array<{
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds?: number;
                loadKg?: number;
                tempo?: string;
                notes?: string;
            }>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/workout-plans';
};

export type PostWorkoutPlansResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type PostWorkoutPlansResponse = PostWorkoutPlansResponses[keyof PostWorkoutPlansResponses];

export type GetStudentsByStudentIdWorkoutPlansData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: never;
    url: '/students/{studentId}/workout-plans';
};

export type GetStudentsByStudentIdWorkoutPlansResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            trainerId: string | null;
            name: string;
            startDate: string | null;
            endDate: string | null;
            status: 'active' | 'archived' | 'draft';
            createdAt: string | string;
        }>;
    };
};

export type GetStudentsByStudentIdWorkoutPlansResponse = GetStudentsByStudentIdWorkoutPlansResponses[keyof GetStudentsByStudentIdWorkoutPlansResponses];

export type DeleteWorkoutPlansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type DeleteWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetWorkoutPlansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type GetWorkoutPlansByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetWorkoutPlansByIdError = GetWorkoutPlansByIdErrors[keyof GetWorkoutPlansByIdErrors];

export type GetWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type GetWorkoutPlansByIdResponse = GetWorkoutPlansByIdResponses[keyof GetWorkoutPlansByIdResponses];

export type PatchWorkoutPlansByIdData = {
    body: {
        name?: string;
        startDate?: string;
        endDate?: string;
        status?: 'active' | 'archived' | 'draft';
        notes?: string;
        days?: Array<{
            label: string;
            dayOrder: number;
            exercises: Array<{
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds?: number;
                loadKg?: number;
                tempo?: string;
                notes?: string;
            }>;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type PatchWorkoutPlansByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchWorkoutPlansByIdError = PatchWorkoutPlansByIdErrors[keyof PatchWorkoutPlansByIdErrors];

export type PatchWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type PatchWorkoutPlansByIdResponse = PatchWorkoutPlansByIdResponses[keyof PatchWorkoutPlansByIdResponses];

export type PostWorkoutLogsData = {
    body: {
        workoutDayId: string;
        date: string;
    };
    path?: never;
    query?: never;
    url: '/workout-logs';
};

export type PostWorkoutLogsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PostWorkoutLogsError = PostWorkoutLogsErrors[keyof PostWorkoutLogsErrors];

export type PostWorkoutLogsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
    };
};

export type PostWorkoutLogsResponse = PostWorkoutLogsResponses[keyof PostWorkoutLogsResponses];

export type PatchWorkoutLogsByIdFinishData = {
    body: {
        durationMin: number;
        rpe?: number;
        notes?: string;
        completed?: boolean;
        sets: Array<{
            workoutExerciseId: string;
            setNumber: number;
            repsDone?: number;
            loadKg?: number;
            completed?: boolean;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-logs/{id}/finish';
};

export type PatchWorkoutLogsByIdFinishErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PatchWorkoutLogsByIdFinishError = PatchWorkoutLogsByIdFinishErrors[keyof PatchWorkoutLogsByIdFinishErrors];

export type PatchWorkoutLogsByIdFinishResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
        notes: string | null;
        sets: Array<{
            id: string;
            workoutLogId: string;
            workoutExerciseId: string;
            setNumber: number;
            repsDone: number | null;
            loadKg: string | number | null;
            completed: boolean;
            exercise: {
                id: string;
                name: string;
            };
        }>;
    };
};

export type PatchWorkoutLogsByIdFinishResponse = PatchWorkoutLogsByIdFinishResponses[keyof PatchWorkoutLogsByIdFinishResponses];

export type GetWorkoutLogsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-logs/{id}';
};

export type GetWorkoutLogsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetWorkoutLogsByIdError = GetWorkoutLogsByIdErrors[keyof GetWorkoutLogsByIdErrors];

export type GetWorkoutLogsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
        notes: string | null;
        sets: Array<{
            id: string;
            workoutLogId: string;
            workoutExerciseId: string;
            setNumber: number;
            repsDone: number | null;
            loadKg: string | number | null;
            completed: boolean;
            exercise: {
                id: string;
                name: string;
            };
        }>;
    };
};

export type GetWorkoutLogsByIdResponse = GetWorkoutLogsByIdResponses[keyof GetWorkoutLogsByIdResponses];

export type GetStudentsByStudentIdWorkoutLogsData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: {
        from?: string;
        to?: string;
        limit?: number;
        offset?: number;
    };
    url: '/students/{studentId}/workout-logs';
};

export type GetStudentsByStudentIdWorkoutLogsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            workoutDayId: string;
            date: string;
            durationMin: number | null;
            rpe: number | null;
            completed: boolean;
            createdAt: string | string;
        }>;
    };
};

export type GetStudentsByStudentIdWorkoutLogsResponse = GetStudentsByStudentIdWorkoutLogsResponses[keyof GetStudentsByStudentIdWorkoutLogsResponses];

export type GetTrainerSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainer/summary';
};

export type GetTrainerSummaryResponses = {
    /**
     * Default Response
     */
    200: {
        students: {
            total: number;
            active: number;
            paused: number;
            inactive: number;
            newThisWeek: number;
        };
        workouts: {
            activePlans: number;
        };
        assessments: {
            last30d: number;
        };
    };
};

export type GetTrainerSummaryResponse = GetTrainerSummaryResponses[keyof GetTrainerSummaryResponses];
