// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3333' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: {
        status: 'ok';
        uptime: number;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostApiAuthSignUpEmailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sign-up/email';
};

export type PostApiAuthSignUpEmailResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiAuthSignInEmailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sign-in/email';
};

export type PostApiAuthSignInEmailResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiAuthBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/auth/{*}';
};

export type GetApiAuthBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiAuthBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/api/auth/{*}';
};

export type PostApiAuthBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetTrainerSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainers/me/subscription';
};

export type GetTrainerSubscriptionResponses = {
    /**
     * Default Response
     */
    200: {
        catalog: {
            free: {
                activeStudentLimit: number | null;
                monthlyPriceCents: number;
                annualPriceCents: number;
            };
            starter: {
                activeStudentLimit: number | null;
                monthlyPriceCents: number;
                annualPriceCents: number;
            };
            pro: {
                activeStudentLimit: number | null;
                monthlyPriceCents: number;
                annualPriceCents: number;
            };
            team: {
                activeStudentLimit: number | null;
                monthlyPriceCents: number;
                annualPriceCents: number;
            };
        };
        subscription: {
            plan: 'free' | 'starter' | 'pro' | 'team';
            billingInterval: 'monthly' | 'annual';
            status: 'active' | 'canceled';
            startsAt: string;
            renewsAt: string | null;
        };
        usage: {
            activeStudents: number;
            activeStudentLimit: number | null;
        };
        invoices: Array<{
            id: string;
            trainerId: string;
            plan: 'free' | 'starter' | 'pro' | 'team';
            billingInterval: 'monthly' | 'annual';
            amountCents: number;
            currency?: string;
            status: 'issued' | 'paid' | 'void';
            issuedAt: string;
            paidAt: string | null;
            createdAt: string;
        }>;
    };
};

export type GetTrainerSubscriptionResponse = GetTrainerSubscriptionResponses[keyof GetTrainerSubscriptionResponses];

export type UpdateTrainerSubscriptionData = {
    body: {
        plan: 'free' | 'starter' | 'pro' | 'team';
        billingInterval: 'monthly' | 'annual';
    };
    path?: never;
    query?: never;
    url: '/trainers/me/subscription';
};

export type UpdateTrainerSubscriptionErrors = {
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type UpdateTrainerSubscriptionError = UpdateTrainerSubscriptionErrors[keyof UpdateTrainerSubscriptionErrors];

export type UpdateTrainerSubscriptionResponses = {
    /**
     * Default Response
     */
    200: {
        subscription: {
            plan: 'free' | 'starter' | 'pro' | 'team';
            billingInterval: 'monthly' | 'annual';
            status: 'active' | 'canceled';
            startsAt: string;
            renewsAt: string | null;
        };
        invoice: {
            id: string;
            trainerId: string;
            plan: 'free' | 'starter' | 'pro' | 'team';
            billingInterval: 'monthly' | 'annual';
            amountCents: number;
            currency?: string;
            status: 'issued' | 'paid' | 'void';
            issuedAt: string;
            paidAt: string | null;
            createdAt: string;
        } | null;
    };
};

export type UpdateTrainerSubscriptionResponse = UpdateTrainerSubscriptionResponses[keyof UpdateTrainerSubscriptionResponses];

export type GetTrainerInvoiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/trainers/me/invoices/{id}';
};

export type GetTrainerInvoiceErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetTrainerInvoiceError = GetTrainerInvoiceErrors[keyof GetTrainerInvoiceErrors];

export type GetTrainerInvoiceResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string;
        plan: 'free' | 'starter' | 'pro' | 'team';
        billingInterval: 'monthly' | 'annual';
        amountCents: number;
        currency?: string;
        status: 'issued' | 'paid' | 'void';
        issuedAt: string;
        paidAt: string | null;
        createdAt: string;
    };
};

export type GetTrainerInvoiceResponse = GetTrainerInvoiceResponses[keyof GetTrainerInvoiceResponses];

export type GetTrainerNotificationPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainers/me/notification-preferences';
};

export type GetTrainerNotificationPreferencesResponses = {
    /**
     * Default Response
     */
    200: {
        inactivity: {
            enabled: boolean;
            afterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        workoutPlanExpiring: {
            enabled: boolean;
            daysBefore?: number;
            channel?: 'email' | 'push' | 'both';
        };
        pendingAssessment: {
            enabled: boolean;
            staleAfterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        newStudentRegistration: {
            enabled: boolean;
            channel?: 'email' | 'push' | 'both';
        };
    };
};

export type GetTrainerNotificationPreferencesResponse = GetTrainerNotificationPreferencesResponses[keyof GetTrainerNotificationPreferencesResponses];

export type UpdateTrainerNotificationPreferencesData = {
    body: {
        inactivity?: {
            enabled?: boolean;
            afterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        workoutPlanExpiring?: {
            enabled?: boolean;
            daysBefore?: number;
            channel?: 'email' | 'push' | 'both';
        };
        pendingAssessment?: {
            enabled?: boolean;
            staleAfterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        newStudentRegistration?: {
            enabled?: boolean;
            channel?: 'email' | 'push' | 'both';
        };
    };
    path?: never;
    query?: never;
    url: '/trainers/me/notification-preferences';
};

export type UpdateTrainerNotificationPreferencesResponses = {
    /**
     * Default Response
     */
    200: {
        inactivity: {
            enabled: boolean;
            afterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        workoutPlanExpiring: {
            enabled: boolean;
            daysBefore?: number;
            channel?: 'email' | 'push' | 'both';
        };
        pendingAssessment: {
            enabled: boolean;
            staleAfterDays?: number;
            channel?: 'email' | 'push' | 'both';
        };
        newStudentRegistration: {
            enabled: boolean;
            channel?: 'email' | 'push' | 'both';
        };
    };
};

export type UpdateTrainerNotificationPreferencesResponse = UpdateTrainerNotificationPreferencesResponses[keyof UpdateTrainerNotificationPreferencesResponses];

export type GetStudentReportData = {
    body?: never;
    path: {
        studentId: string;
    };
    query: {
        range: '30d' | '90d' | '6m' | 'all' | 'custom';
        from?: string;
        to?: string;
    };
    url: '/reports/students/{studentId}';
};

export type GetStudentReportErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetStudentReportError = GetStudentReportErrors[keyof GetStudentReportErrors];

export type GetStudentReportResponses = {
    /**
     * Default Response
     */
    200: {
        student: {
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        period: {
            range: '30d' | '90d' | '6m' | 'all' | 'custom';
            from: string | null;
            to: string | null;
        };
        physicalEvolution: {
            hasEnoughData: boolean;
            points: Array<{
                date: string;
                weightKg: number | null;
                bodyFatPct: number | null;
                measurements: {
                    [key: string]: number;
                } | null;
            }>;
            changes: {
                weightKg: number | null;
                bodyFatPct: number | null;
                waistCm: number | null;
                armCm: number | null;
            };
        };
        beforeAfter: {
            hasEnoughData: boolean;
            before: {
                date: string;
                photoUrl: string | null;
            } | null;
            after: {
                date: string;
                photoUrl: string | null;
            } | null;
        };
        workoutAdherence: {
            hasEnoughData: boolean;
            completed: number;
            planned: number;
            percentage: number | null;
        };
        trainingFrequency: {
            hasEnoughData: boolean;
            days: Array<{
                date: string;
                count: number;
            }>;
        };
        topExercises: {
            hasEnoughData: boolean;
            items: Array<{
                exerciseId: string;
                name: string;
                maxLoadKg: number | null;
                totalSets: number;
                totalVolumeKg: number;
                progression: Array<{
                    date: string;
                    loadKg: number;
                }>;
            }>;
        };
        rpeTrend: {
            hasEnoughData: boolean;
            points: Array<{
                date: string;
                averageRpe: number;
            }>;
        };
        summary: string;
    };
};

export type GetStudentReportResponse = GetStudentReportResponses[keyof GetStudentReportResponses];

export type PostStudentsMePushTokenData = {
    body: {
        token: string;
    };
    path?: never;
    query?: never;
    url: '/students/me/push-token';
};

export type PostStudentsMePushTokenResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetStudentsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        status?: 'active' | 'inactive' | 'paused';
        limit?: number;
        offset?: number;
    };
    url: '/students';
};

export type GetStudentsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            trainerId: string | null;
            isIndependent: boolean;
            name: string;
            email: string | null;
            phone: string | null;
            birthDate: string | null;
            gender: 'male' | 'female' | 'other';
            goals: string | null;
            restrictions: string | null;
            status: 'active' | 'inactive' | 'paused';
            avatarUrl: string | null;
            expoPushToken: string | null;
            createdAt: string;
        }>;
        total: number;
    };
};

export type GetStudentsResponse = GetStudentsResponses[keyof GetStudentsResponses];

export type PostStudentsData = {
    body: {
        name: string;
        email?: string;
        phone?: string;
        birthDate?: string;
        gender?: 'male' | 'female' | 'other';
        goals?: string;
        restrictions?: string;
        status?: 'active' | 'inactive' | 'paused';
    };
    path?: never;
    query?: never;
    url: '/students';
};

export type PostStudentsErrors = {
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PostStudentsError = PostStudentsErrors[keyof PostStudentsErrors];

export type PostStudentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        expoPushToken: string | null;
        createdAt: string;
    };
};

export type PostStudentsResponse = PostStudentsResponses[keyof PostStudentsResponses];

export type DeleteStudentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type DeleteStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetStudentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type GetStudentsByIdErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetStudentsByIdError = GetStudentsByIdErrors[keyof GetStudentsByIdErrors];

export type GetStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        expoPushToken: string | null;
        createdAt: string;
    };
};

export type GetStudentsByIdResponse = GetStudentsByIdResponses[keyof GetStudentsByIdResponses];

export type PatchStudentsByIdData = {
    body: {
        name?: string;
        email?: string;
        phone?: string;
        birthDate?: string;
        gender?: 'male' | 'female' | 'other';
        goals?: string;
        restrictions?: string;
        status?: 'active' | 'inactive' | 'paused';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type PatchStudentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PatchStudentsByIdError = PatchStudentsByIdErrors[keyof PatchStudentsByIdErrors];

export type PatchStudentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        isIndependent: boolean;
        name: string;
        email: string | null;
        phone: string | null;
        birthDate: string | null;
        gender: 'male' | 'female' | 'other';
        goals: string | null;
        restrictions: string | null;
        status: 'active' | 'inactive' | 'paused';
        avatarUrl: string | null;
        expoPushToken: string | null;
        createdAt: string;
    };
};

export type PatchStudentsByIdResponse = PatchStudentsByIdResponses[keyof PatchStudentsByIdResponses];

export type GetExercisesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        muscleGroup?: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment?: string;
        scope?: 'mine' | 'global' | 'all';
        limit?: number;
        offset?: number;
    };
    url: '/exercises';
};

export type GetExercisesResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            trainerId: string | null;
            name: string;
            muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
            equipment: string | null;
            videoUrl: string | null;
            instructions: string | null;
            createdAt: string | string;
        }>;
        total: number;
    };
};

export type GetExercisesResponse = GetExercisesResponses[keyof GetExercisesResponses];

export type PostExercisesData = {
    body: {
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment?: string;
        videoUrl?: string;
        instructions?: string;
    };
    path?: never;
    query?: never;
    url: '/exercises';
};

export type PostExercisesResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        trainerId: string | null;
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment: string | null;
        videoUrl: string | null;
        instructions: string | null;
        createdAt: string | string;
    };
};

export type PostExercisesResponse = PostExercisesResponses[keyof PostExercisesResponses];

export type DeleteExercisesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type DeleteExercisesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchExercisesByIdData = {
    body: {
        name?: string;
        muscleGroup?: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment?: string;
        videoUrl?: string;
        instructions?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type PatchExercisesByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchExercisesByIdError = PatchExercisesByIdErrors[keyof PatchExercisesByIdErrors];

export type PatchExercisesByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        trainerId: string | null;
        name: string;
        muscleGroup: 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps' | 'legs' | 'glutes' | 'core' | 'cardio' | 'full_body';
        equipment: string | null;
        videoUrl: string | null;
        instructions: string | null;
        createdAt: string | string;
    };
};

export type PatchExercisesByIdResponse = PatchExercisesByIdResponses[keyof PatchExercisesByIdResponses];

export type GetTrainerProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainers/me';
};

export type GetTrainerProfileErrors = {
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
};

export type GetTrainerProfileError = GetTrainerProfileErrors[keyof GetTrainerProfileErrors];

export type GetTrainerProfileResponses = {
    /**
     * Default Response
     */
    200: {
        name: string;
        email: string;
        phone: string | null;
        bio: string | null;
        specialties: Array<string>;
        avatarUrl: string | null;
        id: string;
        plan: 'free' | 'starter' | 'pro' | 'team';
        onboardedAt: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetTrainerProfileResponse = GetTrainerProfileResponses[keyof GetTrainerProfileResponses];

export type UpdateTrainerProfileData = {
    body: {
        name?: string;
        email?: string;
        phone?: string | null;
        bio?: string | null;
        specialties?: Array<string>;
        avatarUrl?: string | null;
    };
    path?: never;
    query?: never;
    url: '/trainers/me';
};

export type UpdateTrainerProfileErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    409: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
};

export type UpdateTrainerProfileError = UpdateTrainerProfileErrors[keyof UpdateTrainerProfileErrors];

export type UpdateTrainerProfileResponses = {
    /**
     * Default Response
     */
    200: {
        name: string;
        email: string;
        phone: string | null;
        bio: string | null;
        specialties: Array<string>;
        avatarUrl: string | null;
        id: string;
        plan: 'free' | 'starter' | 'pro' | 'team';
        onboardedAt: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateTrainerProfileResponse = UpdateTrainerProfileResponses[keyof UpdateTrainerProfileResponses];

export type PostTrainersOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainers/onboarding';
};

export type PostTrainersOnboardingResponses = {
    /**
     * Default Response
     */
    200: {
        onboardedAt: string;
    };
};

export type PostTrainersOnboardingResponse = PostTrainersOnboardingResponses[keyof PostTrainersOnboardingResponses];

export type GetStudentsMeAssessmentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/students/me/assessments';
};

export type GetStudentsMeAssessmentsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            date: string;
            weightKg: string | number | null;
            heightCm: string | number | null;
            bodyFatPct: string | number | null;
            measurements: {
                chest?: number;
                waist?: number;
                hip?: number;
                armRight?: number;
                armLeft?: number;
                thighRight?: number;
                thighLeft?: number;
                calfRight?: number;
                calfLeft?: number;
            } | null;
            photos: Array<string> | null;
            notes: string | null;
            createdAt: string | string;
        }>;
        total: number;
    };
};

export type GetStudentsMeAssessmentsResponse = GetStudentsMeAssessmentsResponses[keyof GetStudentsMeAssessmentsResponses];

export type PostStudentsMeAssessmentsData = {
    body: {
        date: string;
        weightKg?: number;
        heightCm?: number;
        bodyFatPct?: number;
        measurements?: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        };
        photos?: Array<string>;
        notes?: string;
    };
    path?: never;
    query?: never;
    url: '/students/me/assessments';
};

export type PostStudentsMeAssessmentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type PostStudentsMeAssessmentsResponse = PostStudentsMeAssessmentsResponses[keyof PostStudentsMeAssessmentsResponses];

export type GetStudentsByStudentIdAssessmentsData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/students/{studentId}/assessments';
};

export type GetStudentsByStudentIdAssessmentsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            date: string;
            weightKg: string | number | null;
            heightCm: string | number | null;
            bodyFatPct: string | number | null;
            measurements: {
                chest?: number;
                waist?: number;
                hip?: number;
                armRight?: number;
                armLeft?: number;
                thighRight?: number;
                thighLeft?: number;
                calfRight?: number;
                calfLeft?: number;
            } | null;
            photos: Array<string> | null;
            notes: string | null;
            createdAt: string | string;
        }>;
        total: number;
    };
};

export type GetStudentsByStudentIdAssessmentsResponse = GetStudentsByStudentIdAssessmentsResponses[keyof GetStudentsByStudentIdAssessmentsResponses];

export type PostStudentsByStudentIdAssessmentsData = {
    body: {
        date: string;
        weightKg?: number;
        heightCm?: number;
        bodyFatPct?: number;
        measurements?: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        };
        photos?: Array<string>;
        notes?: string;
    };
    path: {
        studentId: string;
    };
    query?: never;
    url: '/students/{studentId}/assessments';
};

export type PostStudentsByStudentIdAssessmentsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type PostStudentsByStudentIdAssessmentsResponse = PostStudentsByStudentIdAssessmentsResponses[keyof PostStudentsByStudentIdAssessmentsResponses];

export type DeleteAssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type DeleteAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type GetAssessmentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetAssessmentsByIdError = GetAssessmentsByIdErrors[keyof GetAssessmentsByIdErrors];

export type GetAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type GetAssessmentsByIdResponse = GetAssessmentsByIdResponses[keyof GetAssessmentsByIdResponses];

export type PatchAssessmentsByIdData = {
    body: {
        date?: string;
        weightKg?: number;
        heightCm?: number;
        bodyFatPct?: number;
        measurements?: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        };
        photos?: Array<string>;
        notes?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/assessments/{id}';
};

export type PatchAssessmentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchAssessmentsByIdError = PatchAssessmentsByIdErrors[keyof PatchAssessmentsByIdErrors];

export type PatchAssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        date: string;
        weightKg: string | number | null;
        heightCm: string | number | null;
        bodyFatPct: string | number | null;
        measurements: {
            chest?: number;
            waist?: number;
            hip?: number;
            armRight?: number;
            armLeft?: number;
            thighRight?: number;
            thighLeft?: number;
            calfRight?: number;
            calfLeft?: number;
        } | null;
        photos: Array<string> | null;
        notes: string | null;
        createdAt: string | string;
    };
};

export type PatchAssessmentsByIdResponse = PatchAssessmentsByIdResponses[keyof PatchAssessmentsByIdResponses];

export type PostWorkoutPlansData = {
    body: {
        studentId: string;
        name: string;
        startDate?: string;
        endDate?: string;
        status?: 'active' | 'archived' | 'draft';
        notes?: string;
        days: Array<{
            label: string;
            dayOrder: number;
            exercises: Array<{
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds?: number;
                loadKg?: number;
                tempo?: string;
                notes?: string;
            }>;
        }>;
    };
    path?: never;
    query?: never;
    url: '/workout-plans';
};

export type PostWorkoutPlansResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type PostWorkoutPlansResponse = PostWorkoutPlansResponses[keyof PostWorkoutPlansResponses];

export type GetStudentsMeWorkoutPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/students/me/workout-plans';
};

export type GetStudentsMeWorkoutPlansResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            trainerId: string | null;
            name: string;
            startDate: string | null;
            endDate: string | null;
            status: 'active' | 'archived' | 'draft';
            createdAt: string | string;
            days: Array<{
                id: string;
                planId: string;
                label: string;
                dayOrder: number;
            }>;
        }>;
    };
};

export type GetStudentsMeWorkoutPlansResponse = GetStudentsMeWorkoutPlansResponses[keyof GetStudentsMeWorkoutPlansResponses];

export type GetStudentsByStudentIdWorkoutPlansData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: never;
    url: '/students/{studentId}/workout-plans';
};

export type GetStudentsByStudentIdWorkoutPlansResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            trainerId: string | null;
            name: string;
            startDate: string | null;
            endDate: string | null;
            status: 'active' | 'archived' | 'draft';
            createdAt: string | string;
            days: Array<{
                id: string;
                planId: string;
                label: string;
                dayOrder: number;
            }>;
        }>;
    };
};

export type GetStudentsByStudentIdWorkoutPlansResponse = GetStudentsByStudentIdWorkoutPlansResponses[keyof GetStudentsByStudentIdWorkoutPlansResponses];

export type DeleteWorkoutPlansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type DeleteWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetWorkoutPlansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type GetWorkoutPlansByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetWorkoutPlansByIdError = GetWorkoutPlansByIdErrors[keyof GetWorkoutPlansByIdErrors];

export type GetWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type GetWorkoutPlansByIdResponse = GetWorkoutPlansByIdResponses[keyof GetWorkoutPlansByIdResponses];

export type PatchWorkoutPlansByIdData = {
    body: {
        name?: string;
        startDate?: string;
        endDate?: string;
        status?: 'active' | 'archived' | 'draft';
        notes?: string;
        days?: Array<{
            label: string;
            dayOrder: number;
            exercises: Array<{
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds?: number;
                loadKg?: number;
                tempo?: string;
                notes?: string;
            }>;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-plans/{id}';
};

export type PatchWorkoutPlansByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PatchWorkoutPlansByIdError = PatchWorkoutPlansByIdErrors[keyof PatchWorkoutPlansByIdErrors];

export type PatchWorkoutPlansByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        trainerId: string | null;
        name: string;
        startDate: string | null;
        endDate: string | null;
        status: 'active' | 'archived' | 'draft';
        notes: string | null;
        createdAt: string | string;
        days: Array<{
            id: string;
            planId: string;
            label: string;
            dayOrder: number;
            exercises: Array<{
                id: string;
                workoutDayId: string;
                exerciseId: string;
                exerciseOrder: number;
                sets: number;
                reps: string;
                restSeconds: number | null;
                loadKg: string | number | null;
                tempo: string | null;
                notes: string | null;
                exercise: {
                    id: string;
                    name: string;
                    muscleGroup: string;
                };
            }>;
        }>;
    };
};

export type PatchWorkoutPlansByIdResponse = PatchWorkoutPlansByIdResponses[keyof PatchWorkoutPlansByIdResponses];

export type PostWorkoutLogsData = {
    body: {
        workoutDayId: string;
        date: string;
    };
    path?: never;
    query?: never;
    url: '/workout-logs';
};

export type PostWorkoutLogsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PostWorkoutLogsError = PostWorkoutLogsErrors[keyof PostWorkoutLogsErrors];

export type PostWorkoutLogsResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
    };
};

export type PostWorkoutLogsResponse = PostWorkoutLogsResponses[keyof PostWorkoutLogsResponses];

export type PatchWorkoutLogsByIdFinishData = {
    body: {
        durationMin: number;
        rpe?: number;
        notes?: string;
        completed?: boolean;
        sets: Array<{
            workoutExerciseId: string;
            setNumber: number;
            repsDone?: number;
            loadKg?: number;
            completed?: boolean;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-logs/{id}/finish';
};

export type PatchWorkoutLogsByIdFinishErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PatchWorkoutLogsByIdFinishError = PatchWorkoutLogsByIdFinishErrors[keyof PatchWorkoutLogsByIdFinishErrors];

export type PatchWorkoutLogsByIdFinishResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
        notes: string | null;
        sets: Array<{
            id: string;
            workoutLogId: string;
            workoutExerciseId: string;
            setNumber: number;
            repsDone: number | null;
            loadKg: string | number | null;
            completed: boolean;
            exercise: {
                id: string;
                name: string;
            };
        }>;
    };
};

export type PatchWorkoutLogsByIdFinishResponse = PatchWorkoutLogsByIdFinishResponses[keyof PatchWorkoutLogsByIdFinishResponses];

export type GetWorkoutLogsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workout-logs/{id}';
};

export type GetWorkoutLogsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetWorkoutLogsByIdError = GetWorkoutLogsByIdErrors[keyof GetWorkoutLogsByIdErrors];

export type GetWorkoutLogsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        studentId: string;
        workoutDayId: string;
        date: string;
        durationMin: number | null;
        rpe: number | null;
        completed: boolean;
        createdAt: string | string;
        notes: string | null;
        sets: Array<{
            id: string;
            workoutLogId: string;
            workoutExerciseId: string;
            setNumber: number;
            repsDone: number | null;
            loadKg: string | number | null;
            completed: boolean;
            exercise: {
                id: string;
                name: string;
            };
        }>;
    };
};

export type GetWorkoutLogsByIdResponse = GetWorkoutLogsByIdResponses[keyof GetWorkoutLogsByIdResponses];

export type GetStudentsMeWorkoutLogsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        limit?: number;
        offset?: number;
    };
    url: '/students/me/workout-logs';
};

export type GetStudentsMeWorkoutLogsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            workoutDayId: string;
            date: string;
            durationMin: number | null;
            rpe: number | null;
            completed: boolean;
            createdAt: string | string;
        }>;
    };
};

export type GetStudentsMeWorkoutLogsResponse = GetStudentsMeWorkoutLogsResponses[keyof GetStudentsMeWorkoutLogsResponses];

export type GetStudentsByStudentIdWorkoutLogsData = {
    body?: never;
    path: {
        studentId: string;
    };
    query?: {
        from?: string;
        to?: string;
        limit?: number;
        offset?: number;
    };
    url: '/students/{studentId}/workout-logs';
};

export type GetStudentsByStudentIdWorkoutLogsResponses = {
    /**
     * Default Response
     */
    200: {
        items: Array<{
            id: string;
            studentId: string;
            workoutDayId: string;
            date: string;
            durationMin: number | null;
            rpe: number | null;
            completed: boolean;
            createdAt: string | string;
        }>;
    };
};

export type GetStudentsByStudentIdWorkoutLogsResponse = GetStudentsByStudentIdWorkoutLogsResponses[keyof GetStudentsByStudentIdWorkoutLogsResponses];

export type GetTrainerSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainer/summary';
};

export type GetTrainerSummaryResponses = {
    /**
     * Default Response
     */
    200: {
        students: {
            total: number;
            active: number;
            paused: number;
            inactive: number;
            newThisWeek: number;
            inactive7d: number;
        };
        workouts: {
            activePlans: number;
            expiringThisWeek: number;
        };
        assessments: {
            last30d: number;
            pending: number;
        };
    };
};

export type GetTrainerSummaryResponse = GetTrainerSummaryResponses[keyof GetTrainerSummaryResponses];

export type PostUploadsPresignData = {
    body: {
        kind: 'assessment-photo' | 'avatar';
        contentType: 'image/jpeg' | 'image/png';
    };
    path?: never;
    query?: never;
    url: '/uploads/presign';
};

export type PostUploadsPresignResponses = {
    /**
     * Default Response
     */
    200: {
        uploadUrl: string;
        publicUrl: string;
        fields: {
            [key: string]: never;
        };
    };
};

export type PostUploadsPresignResponse = PostUploadsPresignResponses[keyof PostUploadsPresignResponses];
